### ISSUE TITLE
Is not compatible with V2.0.0

### ISSUE THREAD

**Issue by marcmacias96** [quasarframework/app-extension-apollo#50]
Extension(@quasar/apollo): is not compatible with @quasar/app v2.0.0. Required version: ^1.1.0

**Comment by philon123** [comment]
Having the same issue. After playing around I found a workaround (not a fix!) that you can do after installing the plugin:

Change dependency by changing following line in file `node_modules/@quasar/quasar-app-extension-apollo/src/index.js`:
`api.compatibleWith('@quasar/app', '^2.0.0')`

Remove the generated HTML code from file `src/index.template.html`:
`<% // added by 'quasar-app-extension-apollo' %>
    <% if (htmlWebpackPlugin.options.ctx.mode.ssr) { %>
      {{{ renderState({ contextKey: 'apolloState', windowKey: '__APOLLO_STATE__' }) }}}
    <% } %>`

This will make `quasar dev` work again and I've confirmed apollo queries working in PWA mode. However, it probably breaks SSR mode, since we deleted that code related to SSR!

To anyone reading this who is qualified to fix the issue, there is an error thrown on the code that I deleted. 
`can't read property "mode" of undefined"` or something similar to that.

**Comment by ejez** [comment]
PR submitted, but without testing, please test and report. https://github.com/quasarframework/app-extension-apollo/pull/52

**Comment by smolinari** [comment]
New version to be released soon. 

Scott

**Comment by smolinari** [comment]
https://github.com/quasarframework/app-extension-apollo/releases/tag/1.0.0-beta.4

Scott

**Comment by alecbardiano** [comment]
hi, I am using quasar version 3 as per my quasar -v (3.0.4) 

can I still use quasar apollo?

**Comment by LeulAria** [comment]
what is the status >>

**Comment by smolinari** [comment]
What is the status of what?

Scott

**Comment by LeulAria** [comment]
> What is the status of what?
> 
> Scott

The issue obviously

**Comment by LeulAria** [comment]
any way moved i on to vue-urql
