### ISSUE TITLE
Why not listed on official app extension page?

### ISSUE THREAD

**Issue by MichaelJCole** [quasarframework/app-extension-apollo#75]
Hey, I found this repo on github, but it is not listed on the [official app extensions page](https://quasar.dev/app-extensions/discover#Community-App-Extensions).

Is this official, incubating, or deprecated?  Thanks!

**Comment by smolinari** [comment]
It's semi-official. :) It's not listed, because it is still beta and because I've not been able to dedicate myself to it. If you are a Quasar contributor, you have to say you can dedicate yourself to the package i.e. if anything goes wrong or people need help, you can definitely support it and them. I currently can't make that commitment. 

Scott

**Comment by smolinari** [comment]
Closing as the question is answered.

Scott
